version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: s3_mysql_db
    environment:
      MYSQL_DATABASE: image_db
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: s3_spring_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/image_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - db